import type { AnalysisResult, DealInput } from './types'

const FOOTER = 'Generated by LJM Deal Analyzer  |  Methodology: Michael Rivera Advisor framework  |  © LJM Homes LLC'

function pct(n: number, d = 1) {
  return `${(n * 100).toFixed(d)}%`
}

export async function generateUnderwritingXlsx(
  deal: DealInput,
  analysis: AnalysisResult
): Promise<Buffer> {
  const XLSX = await import('xlsx')
  const wb = XLSX.utils.book_new()

  const sc = analysis.scenarios
  const ex = analysis.expert
  const exi = analysis.expert_income
  const t12 = analysis.t12
  const pf = analysis.pf
  const addr = [deal.address, deal.city, deal.state, deal.zip_code].filter(Boolean).join(', ')
  const ltvPct = deal.ltv ?? 0.65
  const rate = deal.interest_rate ?? 0.068

  // ── Underwriting Sheet (matches LJM Wexler template) ─────────────────────────
  const u: (string | number)[][] = [
    [`${deal.property_name || 'Property'} — Underwriting Analysis`],
    [`${addr}  |  ${deal.units || '?'} units  |  Built ${deal.year_built || '?'}`],
    [],
    ['Line Item', `${sc[0].label} Cap`, `${sc[1].label} Cap`, `${sc[2].label} Cap`, 'T-12 Actuals', 'Broker PF'],
    ['KEY ASSUMPTIONS & INPUTS'],
    ['Expert Stabilized NOI ($)', ex.noi, ex.noi, ex.noi, t12.noi, pf.noi],
    ['Acquisition Cap Rate', pct(sc[0].cap_rate), pct(sc[1].cap_rate), pct(sc[2].cap_rate),
      analysis.asking.price > 0 ? pct(t12.noi / analysis.asking.price, 1) : '—',
      deal.broker_cap_rate != null ? pct(deal.broker_cap_rate) : '—'],
    ['Unit Count', analysis.units, analysis.units, analysis.units, analysis.units, analysis.units],
    ['CapEx per Unit', sc[0].capex_budget / analysis.units, sc[1].capex_budget / analysis.units, sc[2].capex_budget / analysis.units, '—', '—'],
    ['CapEx Budget Total', sc[0].capex_budget, sc[1].capex_budget, sc[2].capex_budget, '—', '—'],
    [],
    ['MAXIMUM ALLOWABLE OFFER (MAO)'],
    ['MAO (NOI / Cap Rate)', sc[0].mao, sc[1].mao, sc[2].mao, '—', '—'],
    ['MAO per Unit', sc[0].mao_per_unit, sc[1].mao_per_unit, sc[2].mao_per_unit, '—', '—'],
    ['All-in Basis (MAO + CapEx)', sc[0].all_in_basis, sc[1].all_in_basis, sc[2].all_in_basis, '—', '—'],
    [],
    ['DEBT STACK'],
    ['LTV (Loan-to-Value)', pct(ltvPct), pct(ltvPct), pct(ltvPct), pct(ltvPct), pct(ltvPct)],
    ['Interest Rate', pct(rate), pct(rate), pct(rate), pct(rate), pct(rate)],
    ['Amortization (months)', 360, 360, 360, 360, 360],
    ['Loan Amount', sc[0].loan_amount, sc[1].loan_amount, sc[2].loan_amount, '—', '—'],
    ['Annual Debt Service', sc[0].annual_debt_service, sc[1].annual_debt_service, sc[2].annual_debt_service, '—', '—'],
    ['DSCR', `${sc[0].dscr.toFixed(2)}x`, `${sc[1].dscr.toFixed(2)}x`, `${sc[2].dscr.toFixed(2)}x`, '—', '—'],
    ['DSCR Min 1.25x Check', sc[0].dscr_pass ? 'PASS' : 'FAIL', sc[1].dscr_pass ? 'PASS' : 'FAIL', sc[2].dscr_pass ? 'PASS' : 'FAIL', '—', '—'],
    ['Equity Required (All-in - Loan)', sc[0].equity_required, sc[1].equity_required, sc[2].equity_required, '—', '—'],
    [],
    ['FORCED APPRECIATION & EXIT (24-MONTH OPTIMIZATION)'],
    ['Post-Optimization NOI', sc[0].post_opt_noi, sc[1].post_opt_noi, sc[2].post_opt_noi, sc[0].post_opt_noi, sc[1].post_opt_noi],
    ['Exit Cap (1.5% Compression)', pct(sc[0].exit_cap_rate), pct(sc[1].exit_cap_rate), pct(sc[2].exit_cap_rate), '—', '—'],
    ['Exit Sale Value', sc[0].exit_value, sc[1].exit_value, sc[2].exit_value, '—', '—'],
    ['Equity Created at Sale', sc[0].equity_created, sc[1].equity_created, sc[2].equity_created, '—', '—'],
    [],
    ['GAP TO ASKING PRICE'],
    ['Asking Price', analysis.asking.price],
    ['Gap to MAO (Asking - MAO)', analysis.asking.price - sc[1].mao],
    ['Gap to MAO (% of Asking)', analysis.asking.price > 0 ? pct((analysis.asking.price - sc[1].mao) / analysis.asking.price, 1) : '—'],
    [],
    ['INCOME DETAIL (Expert UW)'],
    ['Gross Rental Income', exi.gross_rental_income],
    ['Utility Reimbursement', exi.utility_reimbursement],
    ['Other Income', exi.other_income],
    ['Gross Potential Income (GPI)', exi.gpi],
    ['Vacancy + Bad Debt', exi.vacancy_bad_debt],
    ['Effective Gross Income (EGI)', exi.egi],
    ['Total OpEx', exi.opex],
    ['Net Operating Income (NOI)', exi.noi],
    ['Expense Ratio', pct(exi.expense_ratio)],
    [],
    ['RED FLAGS & RISK NOTES'],
    ...analysis.risk_register.slice(0, 6).map((r) => {
      const level = r.score >= 16 ? 'HIGH' : r.score >= 10 ? 'MODERATE' : r.score >= 5 ? 'WATCH' : 'LOW'
      return [`  [${level}]  ${r.risk} — ${r.notes}`]
    }),
    [],
    [FOOTER],
  ]
  const wsU = XLSX.utils.aoa_to_sheet(u)
  wsU['!cols'] = [{ wch: 38 }, { wch: 18 }, { wch: 18 }, { wch: 18 }, { wch: 16 }, { wch: 16 }]
  XLSX.utils.book_append_sheet(wb, wsU, 'Underwriting')

  // ── Summary Dashboard Sheet ──────────────────────────────────────────────────
  const gap = analysis.asking.price - sc[1].mao
  const dash: (string | number)[][] = [
    [`${deal.property_name || 'Property'} — Executive Summary`],
    [],
    ['Metric', sc[0].label, sc[1].label, sc[2].label],
    ['MAO', sc[0].mao, sc[1].mao, sc[2].mao],
    ['All-in Basis', sc[0].all_in_basis, sc[1].all_in_basis, sc[2].all_in_basis],
    ['Loan Amount', sc[0].loan_amount, sc[1].loan_amount, sc[2].loan_amount],
    ['Annual Debt Service', sc[0].annual_debt_service, sc[1].annual_debt_service, sc[2].annual_debt_service],
    ['DSCR', `${sc[0].dscr.toFixed(2)}x`, `${sc[1].dscr.toFixed(2)}x`, `${sc[2].dscr.toFixed(2)}x`],
    ['Equity Required', sc[0].equity_required, sc[1].equity_required, sc[2].equity_required],
    ['Exit Value', sc[0].exit_value, sc[1].exit_value, sc[2].exit_value],
    ['Equity Created', sc[0].equity_created, sc[1].equity_created, sc[2].equity_created],
    [],
    ['BOTTOM LINE'],
    [`Verdict: ${analysis.verdict.label}`],
    [`Asking ${fmtMoney(analysis.asking.price)} vs Sc2 MAO ${fmtMoney(sc[1].mao)} (gap ${fmtMoney(gap)})`],
    [`Recommended LOI target: ${sc[1].label} ${fmtMoney(sc[1].mao)} (${fmtMoney(sc[1].mao_per_unit)}/unit)`],
    [`Forced appreciation upside: ${fmtMoney(sc[1].equity_created)} at exit`],
    [],
    [FOOTER],
  ]
  const wsDash = XLSX.utils.aoa_to_sheet(dash)
  wsDash['!cols'] = [{ wch: 44 }, { wch: 18 }, { wch: 18 }, { wch: 18 }]
  XLSX.utils.book_append_sheet(wb, wsDash, 'Summary Dashboard')

  // ── Unit Mix Sheet ───────────────────────────────────────────────────────────
  const unitHeaders = ['Type', 'Baths', '# Units', 'Avg SF', 'Market Rent', 'Actual Rent', 'Total Mo. Rent', 'Total Ann. Rent']
  const unitRows = (deal.unit_mix || []).map((m) => [
    `${m.bed_count}BR`,
    m.bath_count,
    m.unit_count,
    m.avg_sf,
    m.market_rent,
    m.actual_rent,
    m.unit_count * m.actual_rent,
    m.unit_count * m.actual_rent * 12,
  ])
  const wsUnits = XLSX.utils.aoa_to_sheet([unitHeaders, ...unitRows])
  XLSX.utils.book_append_sheet(wb, wsUnits, 'Unit Mix')

  // ── Risk Register Sheet ──────────────────────────────────────────────────────
  const riskRows = analysis.risk_register.map((r, i) => {
    const level = r.score >= 16 ? 'RED' : r.score >= 10 ? 'ORANGE' : r.score >= 5 ? 'YELLOW' : 'GREEN'
    return [i + 1, r.risk, r.severity, r.likelihood, r.score, level, r.notes]
  })
  const wsRisk = XLSX.utils.aoa_to_sheet([
    ['#', 'Risk', 'Sev', 'Like', 'Score', 'Level', 'Notes'],
    ...riskRows,
  ])
  XLSX.utils.book_append_sheet(wb, wsRisk, 'Risk Register')

  const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })
  return Buffer.from(buf)
}

function fmtMoney(n: number): string {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)
}

export async function generateSynthesisXlsx(
  deal: DealInput,
  analysis: AnalysisResult
): Promise<Buffer> {
  const XLSX = await import('xlsx')
  const wb = XLSX.utils.book_new()

  const sc = analysis.scenarios
  const ex = analysis.expert
  const exi = analysis.expert_income
  const t12 = analysis.t12
  const t2 = analysis.broker_t2
  const pf = analysis.pf
  const gap = analysis.asking.gap_to_sc2_mao
  const hasT2 = t2.gpi > 0

  const rows: (string | number)[][] = [
    [`${deal.property_name || 'Property'} — Broker vs Expert Synthesis`],
    [],
    ['Line Item', 'T-12 Actuals', 'Broker T-2', 'Broker PF', 'Expert UW', 'Notes'],
    ['Gross Rental Income', t12.gross_rental_income, hasT2 ? t2.gross_rental_income : '—', pf.gross_rental_income, exi.gross_rental_income, ''],
    ['Utility Reimbursement', t12.utility_reimbursement, hasT2 ? t2.utility_reimbursement : '—', pf.utility_reimbursement, exi.utility_reimbursement, ''],
    ['Other Income', t12.other_income, hasT2 ? t2.other_income : '—', pf.other_income, exi.other_income, ''],
    ['GPI', t12.gpi, hasT2 ? t2.gpi : '—', pf.gpi, exi.gpi, ''],
    ['Vacancy + Bad Debt', t12.vacancy_bad_debt || '(baked in)', '—', pf.vacancy_bad_debt, exi.vacancy_bad_debt, 'LJM applies 9% vacancy + bad debt'],
    ['EGI', t12.egi, hasT2 ? t2.egi : '—', pf.egi, ex.egi, ''],
    ['Total OpEx', t12.opex, hasT2 ? t2.opex : '—', pf.opex, ex.total_opex, 'LJM uses market-rate mgmt + reserves'],
    ['NOI', t12.noi, hasT2 ? t2.noi : '—', pf.noi, ex.noi, ''],
    ['Expense Ratio', pct(t12.expense_ratio), hasT2 ? pct(t2.expense_ratio) : '—', pct(pf.expense_ratio), pct(ex.expense_ratio), ''],
    [],
    ['SCENARIO SUMMARY', sc[0].label, sc[1].label, sc[2].label, '', ''],
    ['Entry Cap', pct(sc[0].cap_rate), pct(sc[1].cap_rate), pct(sc[2].cap_rate), '', ''],
    ['MAO', sc[0].mao, sc[1].mao, sc[2].mao, '', ''],
    ['DSCR', `${sc[0].dscr.toFixed(2)}x`, `${sc[1].dscr.toFixed(2)}x`, `${sc[2].dscr.toFixed(2)}x`, '', ''],
    ['Exit Value', sc[0].exit_value, sc[1].exit_value, sc[2].exit_value, '', ''],
    ['Equity Created', sc[0].equity_created, sc[1].equity_created, sc[2].equity_created, '', ''],
    [],
    ['VERDICT', analysis.verdict.label, '', '', '', `Gap to MAO: ${gap >= 0 ? '+' : ''}${gap.toFixed(0)} (${(analysis.asking.gap_to_sc2_mao_pct * 100).toFixed(1)}%)`],
    [],
    ['Asking Price', analysis.asking.price, '', '', '', ''],
    ['Sc2 MAO (Moderate)', sc[1].mao, '', '', '', ''],
    ['Gap', gap, '', '', '', ''],
    [],
    [FOOTER],
  ]

  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = [{ wch: 24 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 40 }]
  XLSX.utils.book_append_sheet(wb, ws, 'Synthesis')

  const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' })
  return Buffer.from(buf)
}
